twist_mux:
  ros_parameters:
    topics:
      navigation:
      topic: cmd_vel
      timeout: .5
      priority: 10
    joystick:
      topic: cmd_vel_joy
      timeout: .5
      priority: 100